generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Site
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          a_site_admin
    with_doctrine_route:   1
    #actions_base_class:    sfActions
    #i18n_catalogue:        apostrophe

    config:
      list:
        title: Sites Admin
      
      actions: ~
      fields:  ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~